name: Deploy to Staging

on:
  push:
    branches: [staging, develop]
  pull_request:
    branches: [staging]
    types: [closed]

jobs:
  deploy:
    name: Deploy to Staging Environment
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: |
          npm ci
          npm install -g firebase-tools
          
      - name: Run Tests
        run: |
          echo "🧪 Running tests..."
          # npm test (uncomment when tests are ready)
          echo "✅ Tests passed (placeholder)"
          
      - name: Deploy to Staging
        run: |
          echo "🚀 Deploying to Staging environment..."
          cd firebase-migration-package
          firebase deploy \
            --only hosting \
            --project assiduous-staging \
            --token "${{ secrets.FIREBASE_TOKEN }}"
            
      - name: Verify Deployment
        run: |
          echo "🔍 Verifying staging deployment..."
          sleep 10
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://assiduous-staging.web.app)
          if [ "$RESPONSE" = "200" ]; then
            echo "✅ Staging deployment successful (HTTP 200)"
          else
            echo "❌ Staging deployment verification failed (HTTP $RESPONSE)"
            exit 1
          fi
          
      - name: Post Deployment Summary
        if: always()
        run: |
          echo "## 📦 Staging Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Time:** $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "- **URL:** https://assiduous-staging.web.app" >> $GITHUB_STEP_SUMMARY
