name: Firebase Database Operations

on:
  repository_dispatch:
    types: [db_operation]
  workflow_dispatch:
    inputs:
      operation:
        description: 'Database operation to perform (create/read/update/delete)'
        required: true
        default: 'read'
      collection:
        description: 'Firestore collection name'
        required: true
      query:
        description: 'Query parameters (JSON string)'
        required: false
      data:
        description: 'Document data (JSON string)'
        required: false

permissions:
  contents: write
  id-token: write

env:
  FIREBASE_PROJECT_ID: ${{ github.ref == 'refs/heads/main' && secrets.PROD_FIREBASE_PROJECT_ID || secrets.DEV_FIREBASE_PROJECT_ID }}
  FIREBASE_PRIVATE_KEY: ${{ github.ref == 'refs/heads/main' && secrets.PROD_FIREBASE_PRIVATE_KEY || secrets.DEV_FIREBASE_PRIVATE_KEY }}
  FIREBASE_CLIENT_EMAIL: ${{ github.ref == 'refs/heads/main' && secrets.PROD_FIREBASE_CLIENT_EMAIL || secrets.DEV_FIREBASE_CLIENT_EMAIL }}
  ENCRYPTION_KEY: ${{ github.ref == 'refs/heads/main' && secrets.PROD_ENCRYPTION_KEY || secrets.DEV_ENCRYPTION_KEY }}

jobs:
  database_operation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci || npm install
          npm install firebase-admin @google-cloud/firestore

      - name: Create Service Account Key
        run: |
          echo "$FIREBASE_PRIVATE_KEY" > /tmp/firebase-service-account.json
        env:
          FIREBASE_PRIVATE_KEY: ${{ env.FIREBASE_PRIVATE_KEY }}

      - name: Execute Database Operation
        id: db_operation
        run: |
          node ./scripts/firebase-operations.js
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase-service-account.json
          OPERATION: ${{ inputs.operation }}
          COLLECTION: ${{ inputs.collection }}
          QUERY: ${{ inputs.query }}
          DATA: ${{ inputs.data }}
          ENCRYPTION_KEY: ${{ env.ENCRYPTION_KEY }}

      - name: Cleanup
        if: always()
        run: rm -f /tmp/firebase-service-account.json
